[voicemeeter] # Voicemeeter configuration
kind = "potato"
# Locks the Voicemeeter GUI when running
lock = true

[http] # HTTP server configuration
host = "0.0.0.0"
port = 8080

[general]
# Polling interval for paramater updates in seconds
polling_interval = 0.01

[levels] # Level Monitoring
enabled = true
# Polling interval in seconds
polling_interval = 0.05