on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          spec: 'main.spec'
          requirements: 'requirements.txt'
      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /dist/main
