on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          python_ver: '3.6'
          spec: 'main.spec'
          requirements: 'requirements.txt'
